name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  chek_python_style:
    name: Check Python style
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: VisiumCH/check-python-style@main
        with:
          python-version: '3.9'